appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: r/2PKYUdP/SFUlsh6FVn1Tnck0CXb3669wzFMH3nzGQmlqiM/yIAerW5Mpob8BGd98qNRWu1lc167bhDvCqnIlRC6cKZ8hm0p4XAWrql0nvMdBmtQKGV6nDj3UsrSQNlCce93uc7LOsEKkGcGs20nQgJ9zPnE92W6d4O3DBHvF24p17aQfoUhCac/e/zdU6/aqEyzSndtV8dH/AUki2V94b0dFyUOFvO6Al31Ux8vwvC1F2+dBvYE4JCkSAg5PhW81UalMkrpy4+YTM0Z0GO9cSEndWS4u9hbMFcp3KhVHwtQ+FlfBvg9uEa349SaAe9QtP+zqJPwBihY21zaOFSFYNN/OI3Oy+m81DpLETDanycl29dx0MTHjgmbNpT+rIIeVQ/M8SRiji1NUYjgx6VtHnLDRWJ0sY4h5TDVUdQRPlgWRzXNxT0O6eA1S/5YfTw79+3BP0BIpwLg/IedvMHVelpG8XoSKkZBJQpQqVOori5ayQX0bj2gyJuzJ9F2Q6jQ5V+zYAbJL+9ve416zZsG+XnH69CwNSYWDLOcLsL1HZOvEkv8FG262nnajotr6XhJ9OfohBLBu1b1VdCb3DGJPYmBOuuBZuAug5s69mlIUeODDT9jjK8b20sBP2BJox9H98Xak3XBtZ7/6ppr239UoIysCDcJLzuwbO4m9RqFGw=
conda_forge_output_validation: true
